sudo: required

language: php

services:
  - docker

before_install:
  - docker build -t marusan10/composer-with-prestissimo:1.3 1.3
  - docker build tag marusan10/composer-with-prestissimo:1.3 marusan10/composer-with-prestissimo:1
  - docker build tag marusan10/composer-with-prestissimo:1.3 marusan10/composer-with-prestissimo:latest
  - docker run marusan10/composer-with-prestissimo:1.3
  - docker build -t marusan10/composer-with-prestissimo:1.3-alpine 1.3/alpine
  - docker build tag marusan10/composer-with-prestissimo:1.3 marusan10/composer-with-prestissimo:1-alpine
  - docker build tag marusan10/composer-with-prestissimo:1.3 marusan10/composer-with-prestissimo:alpine
  - docker run marusan10/composer-with-prestissimo:1.3-alpine

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push marusan10/composer-with-prestissimo;
    fi

